---
- hosts: gonkulator
  remote_user: root

  tasks:
  - name: SCANS IN PROGRESS
    shell: /usr/local/etc/stig/scripts/scan-NR-rh6.sh
    async: 7200
    poll: 15
#    args:
#      chdir: /usr/local/etc/stig/scripts
#      executable: /bin/bash
